### ISSUE TITLE
Ruby on Rails Group Project

### ISSUE THREAD

**Issue by cvalencia1991** [cvalencia1991/Recipe-App#14]
## This is the Ruby Capstone Project we are going to work with 2 members and we are assigned by:
`#Team member 1`: @cvalencia1991 
`#Team member 2`: @eng-mohamed-eldeeb  
And this is the kanban Link: [Kanban link](https://github.com/users/cvalencia1991/projects/8)

**Comment by thecodechaser** [comment]
## STATUS: APPROVED 🟢

## Hi @cvalencia1991, and @eng-mohamed-eldeeb👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
